### ISSUE TITLE
Major Changes

### ISSUE THREAD

**Issue by kurtaking** [UTSA-ACM/ACM-Website#12]
I have made changes to the homepage branch with major changes to the website.
<br>
These include:
1. Content for entire website
2. Navbar
    a. Updated links and implemented a dropout list for the events. (would love feedback)
    b. Added the current logo
3. Multiple pages
    a. Home
    b. Events
    c. Calendar
    d. Contact
4. Footer
    a. Footer contains img links to facebook, twitter, github, and linkedin
    note: this could be implemented more efficiently. We could create a single footer.html file and call it in
             at the bottom of each page instead of repetitive code.
5. Homepage
    a. Removed the bottom section and created an events page out of that layout
    b. Move "What is our mission" to the main content section on homepage

**Comment by cdminigun** [comment]
Some updates:

Footer has been modularized, all additions for footer based content shall be made in /views/footer.html
I'd possibly recommend increasing the spacing between images and capitalizing the UTSA-ACM in the copyright. Otherwise the logos look great! 

Otherwise all of your other additions look good.
